name: Default
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: make
      - run: make .env
      - run: make verify
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    container: google/cloud-sdk:slim
    environment: production
    env:
      GCLOUD_SERVICE_ACCOUNT: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: make  deploy-file-converter

